apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
  labels:
    app: kuber-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuber-project
  template:
    metadata:
      labels: 
        app: kuber-project
    spec:
      containers:
      - name: result-app
        image: aplicacion:latest  # Asegúrate de especificar la imagen
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
