name: CI

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '12 15 * * *'

jobs:
  sast:
    name: Análisis estático con Semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    container:
      image: semgrep/semgrep:latest

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --code
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  
  sca:
    name: Análisis de composición de software con Semgrep
    runs-on: ubuntu-latest
    needs: sast
    permissions:
      contents: read
    
    container:
      image: semgrep/semgrep:latest

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --supply-chain
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  
  image-docker-scan:
    name: Construcción y escaneo de imagen Docker
    runs-on: ubuntu-latest
    needs: sca

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Construir imagen Docker
        run: |
          docker build -t aplicacion:latest .
      - name: Escaneo de vulnerabilidades con Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: aplicacion:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
  
  deploy-image-local:
    name: Despliegue de imagen en docker local
    runs-on: self-hosted
    needs: image-docker-scan

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t aplicacion:latest .

      - name: Ejecutar contenedor
        shell: bash
        run: |
          docker stop aplicacion
          docker rm aplicacion
          docker run -d --name aplicacion-deploy \
            -e NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            -e NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
            -e NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
            -e NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} \
            -e NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
            -e NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            -e NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
            -p 80:80 aplicacion:latest